name: Restart

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run restart script
        run: bash vm.sh
