name: Sync
on:
  push:
    branches:
      - main  # Set this to the branch you want to sync

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: [actions/checkout](https://github.com)@v4
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          DEST_REPO: "devadarsh22-lgtm/rdp6t7"
          TOKEN: ${{ secrets.Repo }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add destination "https://${TOKEN}@github.com/${DEST_REPO}.git"
          # Sync all branches and tags to the destination
          git push destination main --force
