name: Sync

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          DEST_REPO: "devadarshdev22-lgtm/rdp6t7"
          TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote remove destination || true
          git remote add destination "https://${TOKEN}@github.com/${DEST_REPO}.git"

          git push destination main --force
